#!/usr/bin/ruby

require 'rubygems'
require 'cgi'
require 'date'
require 'json'
require 'net/https'
require 'syslog'

$SAFE=1

def getUserProfile(token)

  apiKey='engage api key'

  rpxURL='https://rpxnow.com/api/v2/auth_info'
  uri = URI(rpxURL)

  http = Net::HTTP.new(uri.host, uri.port)
  http.use_ssl = true
  http.verify_mode = OpenSSL::SSL::VERIFY_PEER

  request = Net::HTTP::Post.new(uri.request_uri)
  request.set_form_data({ 'token' => token, 'apiKey' => apiKey, 'format' => 'json', 'extended' => 'false' })

  response = http.request(request)

  tokenresponse = response.body
  @syslog.info("got response #{tokenresponse}")
  return JSON.parse(response.body)
end

@syslog = Syslog.open("token", Syslog::LOG_PID, Syslog::LOG_USER)

now = DateTime.now

c = CGI.new("html4")

@syslog.info("processing request #{c.params}")

token = c['token']

profile = getUserProfile(token)

stat = profile["stat"]
if (stat == "fail")
  code = profile['err']['code']
  msg = profile['err']['msg']
  @syslog.notice("that's an error: #{code} #{msg}")
  c.out("Content-Type" => 'application/json') { JSON.generate(profile) }
else
  profile["token"] = token
  profile["date"] = now

  displayName = profile["profile"]["displayName"];
  if (displayName.nil?)
    displayName = 'Stranger'
  end
  dNameCookie = CGI::Cookie.new('name' => "cmDisplayName", 'value' => displayName, 'path' => '/')
  profileCookie = CGI::Cookie.new('name' => "cmProfile", 'value' => JSON.generate(profile), 'path' => '/')
  @syslog.info("profile: "+ JSON.generate(profile))
  puts c.header( "cookie" => [dNameCookie, profileCookie], 'status' => '302 Moved', 'Location' => c.referer)
end
